# Generated by Django 6.0.4 on 2026-05-01 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_aboutpage_product_ingredients_order_orderitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('working_hours', models.CharField(blank=True, max_length=100, verbose_name='Часы работы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Пекарня',
                'verbose_name_plural': 'Пекарни',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('processing', 'В работе'), ('ready', 'Готов'), ('delivered', 'Выдан'), ('cancelled', 'Отменён')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='bakery.store', verbose_name='Точка самовывоза'),
        ),
    ]
