# Generated by Django 6.0.4 on 2026-05-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0003_store_alter_order_status_order_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='approved',
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_by_customer',
            field=models.BooleanField(default=False, verbose_name='Отменён заказчиком'),
        ),
        migrations.AddField(
            model_name='review',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Опубликован'), ('rejected', 'Отклонён')], default='pending', max_length=20, verbose_name='Статус модерации'),
        ),
    ]
