# Generated by Django 6.0.4 on 2026-05-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0004_remove_review_approved_order_cancelled_by_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bread', 'Хлеб'), ('pastry', 'Выпечка'), ('fastfood', 'Фастфуд'), ('dessert', 'Десерты'), ('beverage', 'Напитки'), ('salad', 'Салаты'), ('hot_dish', 'Горячее'), ('snack', 'Снеки')], default='bread', max_length=20, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='cuisine',
            field=models.CharField(choices=[('russian', 'Русская кухня'), ('caucasian', 'Кавказская кухня'), ('american', 'Американская кухня'), ('european', 'Европейская кухня'), ('asian', 'Азиатская кухня'), ('mediterranean', 'Средиземноморская кухня'), ('bakery', 'Пекарня')], default='bakery', max_length=20, verbose_name='Кухня'),
        ),
    ]
