# Generated by Django 6.0.4 on 2026-05-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0005_product_category_product_cuisine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cuisine',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.TextField(blank=True, help_text='Теги через запятую: например, хлеб, домашний, полезный', verbose_name='Теги'),
        ),
    ]
