# Generated by Django 6.0.4 on 2026-05-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0006_remove_product_category_remove_product_cuisine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='cuisine_tags',
            field=models.TextField(blank=True, help_text='Через запятую: русская, кавказская, американская, европейская', verbose_name='Тип кухни'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_tags',
            field=models.TextField(blank=True, help_text='Через запятую: хлеб, выпечка, фастфуд, десерты', verbose_name='Тип продукции'),
        ),
    ]
