# Generated by Django 6.0.4 on 2026-05-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0007_remove_product_tags_product_cuisine_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stores/', verbose_name='Фото'),
        ),
    ]
